config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'gossips#index'
  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  validates :anonymous_author, presence: true,
                      length: { minimum: 3 }
  validates :content, presence: true,
                      length: { minimum: 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossips= Gossip.all
  end

  def new
    @gossip= Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if  @gossip.save
      redirect_to @gossip
    else
      render 'new'
    end
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(gossip_params)
          redirect_to @gossip
        else
          render 'edit'
        end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private
    def gossip_params
      params.permit(:anonymous_author, :content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/_form.html.erb
<% if @gossip.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@gossip.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @gossip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= label_tag 'anonymous_author', "Votre pseudo de délateur" %>
<%= text_field_tag 'anonymous_author' %>
<br>
<%= label_tag 'content', 'La rumeur à balancer' %>
<%= text_area_tag 'content' %>

app/views/gossips/edit.html.erb
<h1>Editer le gossip</h1>

<%= form_tag gossip_path(@gossip), method: :put do %>
  <%= render 'form' %>
  <%= submit_tag "Modifier le gossip"%>
<% end %>

<h1>Effacer à jamais le gossip</h1>

<%= link_to 'Cliquer pour détruire', @gossip, method: :delete %>

<%= link_to 'Retour', gossip_path %>

app/views/gossips/index.html.erb
<p> Hello ! <br> et bienvenue sur le site des Gossips de THP !</p>

<p> <a href="/gossips/new">Créer un nouveau gossip</a> </p>

<table>
  <tr>
    <th>ID</th>
    <th>L'auteur</th>
    <th>Son gossip</th>
  </tr>

  <% @gossips.each do |gossip| %>
  <tr>
    <td><%= gossip.id %></td>
    <td><%= gossip.anonymous_author %></td>
    <td><%= gossip.content %></td>
    <td><%= link_to "Montrer le gossip", gossip_path(gossip) %></td>
    <td><%= link_to "Editer", edit_gossip_path(gossip) %></td>
    <td><%= link_to 'Detruire', gossip_path(gossip),
            method: :delete,
            data: { confirm: 'Etes vous sûr de votre acte irréversible ?' } %></td>

  </tr>
  <% end %>
</table>

app/views/gossips/new.html.erb
<h1> Lancer un nouveau gossip</h1>

<%= form_tag (gossips_path) do %>
  <%= render 'form' %>
<br><br>
<%= submit_tag "Lancer !"%>
<% end %>

app/views/gossips/show.html.erb
Un gossip de <%= @gossip.anonymous_author %>
<br>
<p>Voilà ce que ça dit : </p>
<br>
<%= @gossip.content %>

<br>
<p> <%= link_to "Corriger le gossip", edit_gossip_path%></p>
<p> <%= link_to 'Cliquer pour détruire à jamais', gossip_path(@gossip), method: :delete ,
              data: { confirm: 'Etes vous sur ?' }%></p>
<br>
<p> <a href="/">Retourner à l'accueil</a> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>